---
- name: Build Ubuntu 16 Server
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy new Ubuntu 16 VM to Default Group in specified (UC1) datacenter
      clc_server:
        name: test
        template: ubuntu-16-64
        location: UC1
        count: 5
        group: 'Default Group'
      register: clc
    - name: debug
      debug: var=clc.server_ids
   tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
