---
- name: Build Ubuntu 16 Server
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy VM - Ubuntu 16.04
      clc_server:
        name: www
        template: ubuntu-16-64
        location: UC1
        count: 5
        group: 'Web Farm'
      register: clc
    - name: debug
      debug: var=clc.server_ids
